### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by rollecode** [Guilh/Poly#6]
Can you add this to bower? Can't find it http://bower.io/search/?q=poly
I supposed you can name it like `poly-ui-kit`.

**Comment by shelldandy** [comment]
bower packages don't work that way (at least the way of this package)

if they were mixins or functions only then it would make sense to import into your project.

You are not supposed to write inside bower/npm packages this encourages you to write on it soo i don't think so 😁

**Comment by rollecode** [comment]
Wow, forgot about this, it has been more than year. In 2016 it's recommended to add your stuff at least to npm, so I really do recommend to do that.

What do you mean "you are not supposed to write inside bower/npm packages"? of course you should publish this in npm/bower "as is", so that developers can include the core files to their projects.

Controlling CSS versions from the upstream is awkward in my opinion.

**Comment by shelldandy** [comment]
Haha no problem I just came back to check the color-pallete function but let me clarify what i mean by "you are not supposed to write inside bower/npm packages"

Imagine you add this via bower then you start writing inside of it.

If you want to pick where you left on another computer ie: desktop now

You have to do bower install again which would download everything from this repo soo your changes would be overwritten.

So to prevent this you'd have to track changes inside the `bower` or `node_modules` directory, which is against common convention you are supposed to gitignore those directories since you are not maintaining them.

Sooo on sass packages you usually just import them and at most add a variables/settings to tweak your stuff but you do that outside of the install on your own `src` directory

**Comment by shelldandy** [comment]
What would make sense is to either fork/clone this OOOR make it a yeoman generator package.

**Comment by rollecode** [comment]
It feels strange that you are not familiar with this procedure. As a front end developer I (and many others) add the "core" packages in package.json if used npm or bower.json if used bower and do the overwrites in their own scss files. That way we'll get updates to the "core" files and still retain our own modifications.

Forking this doesn't make sense. I just want to use poly as part of my projects, but seems senseless to always have to check up the latest version instead of just `npm update`.

Haven't used yeoman.

I do websites, not apps.

**Comment by shelldandy** [comment]
I am a web and app developer as well 😄 

I think you haven't really used this package that much, this package is meant to be extended as you go since its based on the BEM and SMACSS principles.

It makes sense if you only use the mixins or functions and then you do your own stuff on another folder outside bower.

A good example of something like that would be [Jeet.gs](http://jeet.gs/) or [Modular Scale](https://github.com/modularscale/modularscale-sass/)

So if you already have your own structure of doing css then adding this would not only add the mixins and functions but also all of the classes it made, so would have to overwrite a lot or use uncss.

Yeoman instead asks you what are you going to do and adds the folder structure for you, only installs the relevant npm packages, makes the appropriate gulp tasks etc.

So you can start from that custom point and then keep on working on your own.

A good example of a Yeoman starting point for websites would be the [Pixel2Html-Generator](https://github.com/Pixel2HTML/pixel2html-generator)

**Comment by rollecode** [comment]
User of Jeet AND modular scale here. Yes, you are correct, have not used this package that much. I now understand the principle here, so closing this. Was a nice talk though.
